name: Python Unittest for Model Accuracy

on:
  push:
    branches:
      - test

jobs:
  unittest_model_accuracy:
    name: Unittest for Model Accuracy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run Unittest for model accuracy
      run: |
        python -m unittest test.py
