name: Python Unit Testing

on:
  push:
    branches:
      - test

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run unit tests
      run: |
        python -m unittest test.py
